name: dev
run-name: "CI: ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  VERSION: "1.0.${{ github.run_number }}"

concurrency:
  group: dev-${{ github.ref_name }}

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Version Number
        run: |
          BUILD_DATE=$(date +%Y-%m-%dT%H:%MZ)
          mkdir ./dist
          echo '{
            "VERSION": "'$VERSION'",
            "BUILD_DATE": "'$BUILD_DATE'",
            "SHA": "'$GITHUB_SHA'",
            "GITHUB_REF_NAME": "'$GITHUB_REF_NAME'"
          }' | jq '.' > ./dist/version.json
          jq '.' ./dist/version.json >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./dist
