name: dev
run-name: "Dev"

on:
  push:
    branches:
      - main

concurrency:
  group: dev-${{ github.ref_name }}

jobs:
  # find-user-dirs:
  #   runs-on: ubuntu-latest
  #   # outputs:
  #   #   matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 2
  #     - name: Find changed user directories
  #       id: set-matrix
  #       run: |
  #         changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
  #         # user_dirs=$(echo "$changed_files" | grep '^src/users/' | cut -d'/' -f1-3 | sort -u | jq -R -s -c '{user_dir: .}')
  #         # echo "matrix=$user_dirs" >> $GITHUB_OUTPUT
  #         echo $changed_files
  #       shell: bash

  # list-changed-users:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     users: ${{ steps.list.outputs.users }}
  #   steps:
  #     - name: list
  #       id: list
  #       run: |
  #         # USERS='["src/users/alena", "src/users/nathan"]'
  #         USERS='[]'
  #         echo "users=${USERS}" >> $GITHUB_OUTPUT
  #         echo "has_changes=false" >> $GITHUB_OUTPUT

  # read-name:
  #   needs: list-changed-users
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       user: ${{fromJson(needs.list-changed-users.outputs.users)}}
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #     - name: Read name
  #       run: |
  #         cat ${{ matrix.user }}/name.txt
  list-changed-users:
    runs-on: ubuntu-latest
    outputs:
      users: ${{ steps.list.outputs.users }}
      isChanged: ${{ steps.list.outputs.isChanged }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: List
        id: list
        run: |
          python scripts/list-changed-users.py ${{ github.event.before }} ${{ github.sha }}

  read-name:
    needs: list-changed-users
    if: needs.list-changed-users.outputs.isChanged
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user: ${{fromJson(needs.list-changed-users.outputs.users)}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Read name
        run: |
          cat ${{ matrix.user }}/name.txt
