name: dev
run-name: "Dev"

on:
  push:
    branches:
      - main

concurrency:
  group: dev-${{ github.ref_name }}

jobs:
  read-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cat
        run: cat src/users/nathan/name.txt
