name: dev
run-name: "Dev"

on:
  push:
    branches:
      - main

concurrency:
  group: dev-${{ github.ref_name }}

jobs:
  read-name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: cat
        run: cat src/users/nathan/name.txt
