name: dev

on:
  push:
    branches:
      - main

concurrency:
  group: dev-${{ github.ref_name }}

env:
  PATH_PATTERN: src/users/!(nathan)/*.txt

jobs:
  list-changed-users:
    runs-on: ubuntu-latest
    outputs:
      users: ${{ steps.list.outputs.users }}
      users_files: ${{ steps.list.outputs.users_files }}
    steps:
      - uses: actions/checkout@v4

      - id: list
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            users:
              - added|modified: ${{ env.PATH_PATTERN }}

  read-name:
    needs: list-changed-users
    if: ${{ needs.list-changed-users.outputs.users == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user: ${{fromJson(needs.list-changed-users.outputs.users_files)}}
    steps:
      - uses: actions/checkout@v4

      - name: Read name
        run: |
          dirname ${{ matrix.user }}
          cat ${{ matrix.user }}
