name: dev
run-name: "CI: ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  VERSION: "1.0.${{ github.run_number }}"

concurrency:
  group: dev-${{ github.ref_name }}

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo
        run: |
          BUILD_DATE=$(date +%Y-%m-%dT%H:%MZ)
          echo '{
            "APP_VERSION": "'$APP_VERSION'",
            "BUILD_DATE": "'$BUILD_DATE'",
            "SHA": "'$GITHUB_SHA'",
            "GITHUB_REF_NAME": "'$GITHUB_REF_NAME'"
          }' | jq '.' > ./version.json
          cat version.json
          echo $BUILD_DATE
          echo '{"name": "Alice", "age": 28, "pets": ["cat", "dog", "fish"]}' | jq '.pets[] | select(. != "fish")'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
