name: Sed

on:
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Update version information
        run: |
          BUILD_DATE=$(date -u +'%Y-%m-%d')
          sed -i -e "
            s/<version>/whatever/g;
            s/<date>/${BUILD_DATE}/g;
            s/<sha>/${{ github.sha }}/g
          " ./src/version.ts

      - name: Show file contents before and after
        run: |
          cat ./src/version.ts
