name: Terragrunt Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terragrunt Init
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: "1.1.7"
          tg_actions_version: "v0.36.6"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "src/users/david"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terragrunt Plan
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: 1.0.0
          tg_actions_version: 0.31.0
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "src/users/david"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terragrunt Apply
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: 1.0.0
          tg_actions_version: 0.31.0
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "src/users/david"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terragrunt Output
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: 1.0.0
          tg_actions_version: 0.31.0
          tf_actions_subcommand: "output"
          tf_actions_working_dir: "src/users/david"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
