name: test # CD artifact to test
run-name: "Deploy: ${{ github.event.workflow_run.run_number }}"

on:
  # This workflow is triggered when the dev pipeline completes:
  workflow_run:
    workflows: [dev]
    types: [completed]
    branches: [main]

permissions:
  contents: read
  packages: read
  actions: read

jobs:
  read-version-number:
    runs-on: ubuntu-latest
    outputs:
      version-number: ${{ steps.parse.outputs.version-number }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: parse
        id: parse
        run: |
          jq -r '"version=" + .VERSION' ./dist/version.json
          jq -r '"version-number=" + .VERSION' ./dist/version.json >> "$GITHUB_OUTPUT"

  a:
    runs-on: ubuntu-latest
    needs: read-version-number
    steps:
      - name: a
        run: |
          echo ${{ needs.read-version-number.outputs.version-number }}

  b:
    runs-on: ubuntu-latest
    needs: a
    steps:
      - name: b
        run: |
          echo ${{ needs.read-version-number.outputs.version-number }}
