name: test # CD artifact to test
run-name: "Deploy: ${{ github.event.workflow_run.head_commit.message }}"

on:
  # This workflow is triggered when the dev pipeline completes:
  workflow_run:
    workflows: [dev]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  packages: read
  actions: read

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          run-id: ${{ github.event.workflow_run.id }}
